name: Docker Image CI Install

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file .devcontainer/Dockerfile --tag my-image-name:$(date +%s)
    - name: install requirements
      run: |
        make install
    - name: run linting
      run: |
        make lint
    - name: run formatting (black)
      run: |
        make format
    - name: make pdf
      run: |
        make pdf
    - run: echo "🍏 This job's status is ${{ job.status }}."
